### ISSUE TITLE
electron截屏方法调用时间比较长，有没有解决办法

### ISSUE THREAD

**Issue by kisstherain** [nashaofu/screenshots#1]
发现electron截屏时间比较长，desktopCapturer.getSources在mac上要200ms，windows上要700ms，这个能直接感觉到了，有没有好的办法解决？

**Comment by nashaofu** [comment]
desktopCapturer.getSources这个方法是调的electron封装的原生的，目前还没有好的解决方案

**Comment by xxhong** [comment]
为啥的我mac运行不了demo

**Comment by nashaofu** [comment]
mac上开发好像有点问题，不过界面能出来
