### ISSUE TITLE
Error: 没有获取到输入源

### ISSUE THREAD

**Issue by pangsgithub** [nashaofu/screenshots#104]
调用时提示Error: 没有获取到输入源

**Comment by nashaofu** [comment]
https://github.com/nashaofu/screenshots/blob/v0.1.0/packages/react-screenshots/src/electron/getSnapshotDataURL.js#L13-L17 应该是这里的问题

**Comment by pangsgithub** [comment]
捕获不到屏幕？

**Comment by nashaofu** [comment]
捕获到的source的屏幕id与传入的屏幕id没有匹配上，你可以调试一下看看source. display_id是啥

**Comment by nashaofu** [comment]
你是用最新版本看看能否正常工作
