### ISSUE TITLE
macos下实现文字输入的问题

### ISSUE THREAD

**Issue by JohnnyYeen** [nashaofu/screenshots#113]
我自己也实现了一个类似的截屏工具，但是在macos下会有如下问题：
如果让截屏窗口挡住statusbar（高level），那么就会导致输入法窗口被遮挡。
如果设置窗口level低级别，输入法选择窗可以正常显示，但截屏窗口又挡不住statusbar。
不知道是否有解决的思路？

**Comment by nashaofu** [comment]
![image](https://user-images.githubusercontent.com/19303058/150632320-6e20ce31-0bfc-48ef-92ac-4d8b55d347ab.png)
这个bar吗？

**Comment by JohnnyYeen** [comment]
不是这个，是输入法的选字框会被遮挡。

**Comment by nashaofu** [comment]
我这边是可以的
<img width="972" alt="WX20220425-223933@2x" src="https://user-images.githubusercontent.com/19303058/165112396-d1795b47-eba3-4b90-ad15-4403dac2d905.png">
