### ISSUE TITLE
Custom action title.

### ISSUE THREAD

**Issue by viktor-shmigol** [nashaofu/screenshots#114]
As far as I can see the default language for this plugin is Chinese. Is there any chance to implement a way to support multiple language like English etc?
For instance: if you hover on the any icon in toolbar you will see  the tool tip with Chinese text(See https://github.com/nashaofu/screenshots/blob/master/packages/react-screenshots/src/components/Screenshots/actions/ok.js#L4).
It would be awesome if we have a way to set a custom title while initializing a plugin.
For example:
```
const screenshots = new Screenshots({
  actions: {
    ok: {
      title: 'Okay'
    },
    save: {
      title: 'Save'
    }
  }
})
screenshots.on('ok', (e, { viewer }) => {
  console.log('capture', viewer)
}
```

Thanks!

**Comment by nashaofu** [comment]
OK, I'll consider supporting this feature

**Comment by nashaofu** [comment]
The latest version is already supported，https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#methods

**Comment by viktor-shmigol** [comment]
@nashaofu Awesome. Thanks!
