### ISSUE TITLE
截屏模糊能解决吗

### ISSUE THREAD

**Issue by purple-color** [nashaofu/screenshots#121]
大佬截屏模糊解决一下呗, 很好用就是有点模糊

**Comment by purple-color** [comment]
版本0.2.0

**Comment by nashaofu** [comment]
目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写

**Comment by purple-color** [comment]
期待

**Comment by WenWenBo** [comment]
> 目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写

或者考虑用node去获取截图试一下 @nashaofu ？
https://github.com/bencevans/screenshot-desktop

我试了一下这个截出来的图分辨率会高一些，而且这样就不用渲染进程去截图再把图片传回主进程了，可以尝试看看。

**Comment by nashaofu** [comment]
这个linux需要额外的依赖

**Comment by jsqq520** [comment]
![image](https://user-images.githubusercontent.com/39544880/159668139-0c1d11ba-35c0-4f40-8899-78cb437b4f39.png)
目前添加了一个补丁，背景比之前好些 @nashaofu

**Comment by nashaofu** [comment]
目前正在用rust编写截图部分，mac与windows已经完美支持，linux的还在开发

**Comment by jsqq520** [comment]
能先发一个mac与windows的支持的版本吗？

**Comment by jsqq520** [comment]
能先发一个mac与windows的支持的版本吗？ @nashaofu

**Comment by nashaofu** [comment]
> 能先发一个mac与windows的支持的版本吗？ @nashaofu 

可以，我正在准备了，快的话清明节后就可以用上了

**Comment by BlmVay** [comment]
> 目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写

好像貌似不是electron截图Api返回的图片模糊哎,因为把鼠标放上去的时候(截图,别框选,看鼠标位置的细节图),显示的很清晰,就是在画布上和框选的时候  画质开始低了

**Comment by mlmdflr** [comment]
> > 目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写
> 
> 好像貌似不是electron截图Api返回的图片模糊哎,因为把鼠标放上去的时候(截图,别框选,看鼠标位置的细节图),显示的很清晰,就是在画布上和框选的时候 画质开始低了
> 
> 如图 ![image](https://user-images.githubusercontent.com/30430193/162496004-dfbe1e1d-4d85-4cd6-b23f-6336327eff56.png)

确实,我改用了rust的截图发现跟electron返回的没啥区别(清晰度),唯一的改善是rust截图更加快点....

**Comment by BlmVay** [comment]
> > > 目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写
> > 
> > 
> > 好像貌似不是electron截图Api返回的图片模糊哎,因为把鼠标放上去的时候(截图,别框选,看鼠标位置的细节图),显示的很清晰,就是在画布上和框选的时候 画质开始低了
> > 如图 ![image](https://user-images.githubusercontent.com/30430193/162496004-dfbe1e1d-4d85-4cd6-b23f-6336327eff56.png)
> 
> 确实,我改用了rust的截图发现跟electron返回的没啥区别(清晰度),唯一的改善是rust截图更加快点....

嗯  我查阅了一些资料   可能是和devicePixelRatio，设备像素比有些关系   可以通过获取devicePixelRatio去设置canvas的width和height，然后在样式里固定住canvas的渲染宽高。

**Comment by BlmVay** [comment]
> > > > 目前不能哈，electron截图API返回图片很模糊，后面我这边可能会用原生重写
> > > 
> > > 
> > > 好像貌似不是electron截图Api返回的图片模糊哎,因为把鼠标放上去的时候(截图,别框选,看鼠标位置的细节图),显示的很清晰,就是在画布上和框选的时候 画质开始低了
> > > 如图 ![image](https://user-images.githubusercontent.com/30430193/162496004-dfbe1e1d-4d85-4cd6-b23f-6336327eff56.png)
> > 
> > 
> > 确实,我改用了rust的截图发现跟electron返回的没啥区别(清晰度),唯一的改善是rust截图更加快点....
> 
> 嗯 我查阅了一些资料 可能是和devicePixelRatio，设备像素比有些关系 可以通过获取devicePixelRatio去设置canvas的width和height，然后在样式里固定住canvas的渲染宽高。

也不尽然  也有可能是绘制参数上的优化导致清晰度的丢失

**Comment by nashaofu** [comment]
devicePixelRatio参数也有设置，canvas绘图会重新采样的问题，感觉还是不太好解决

**Comment by nashaofu** [comment]
清晰度最新版本有一点改善，可以看看效果，直接原因是因为canvas缩放图片导致失真

**Comment by Adar-Li** [comment]
> 好&nbsp;感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月25日(星期一) 晚上10:14 收件人: ***@***.***&gt;; 抄送: "🔰BL. ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [nashaofu/screenshots] 截屏模糊能解决吗 (Issue #121) 清晰度最新版本有一点改善，可以看看效果，直接原因是因为canvas缩放图片导致失真 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以关闭下问题了

**Comment by xuwab** [comment]
0.3.2 在 mac 上 debug 是清晰的，打包出来一直是模糊的，有建议吗？🙏

**Comment by xuwab** [comment]
0.3.2 在 mac 上 debug 是清晰的，打包出来一直是模糊的，有建议吗？🙏

**Comment by nashaofu** [comment]
设置环境变量 DEBUG=screenshots，然后截图插件会有日志输出，看看会不会有这个日志输出，`logger('SCREENSHOTS:capturer.capture() error %o', err)`

**Comment by nashaofu** [comment]
> 设置环境变量 DEBUG=screenshots，然后截图插件会有日志输出，看看会不会有这个日志输出，`logger('SCREENSHOTS:capturer.capture() error %o', err)`

最新版本添加了logger参数，你在打包后，log看看有输出`SCREENSHOTS:capturer.capture() error`这个吗？

**Comment by Luca-Hsu** [comment]
> > 设置环境变量 DEBUG=screenshots，然后截图插件会有日志输出，看看会不会有这个日志输出，`logger('SCREENSHOTS:capturer.capture() error %o', err)`
> 
> 最新版本添加了logger参数，你在打包后，log看看有输出`SCREENSHOTS:capturer.capture() error`这个吗？

1、没有日志输出
2、0.3.1 开始 debug 是清晰的，就打包模糊
3、还有现在会报"Error: Cannot find module 'fs/promises'"，我升级node到14也没用，每次都得手动改，能不能参考 [这里](https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly) 兼容下。

谢谢

**Comment by nashaofu** [comment]
electron 版本太低了吧! https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#methods 新版本可以传递logger参数，你看看。

**Comment by Luca-Hsu** [comment]
> electron 版本太低了吧! https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#methods 新版本可以传递logger参数，你看看。
👇使用的版本，需要升级吗
"electron": "11.3.0",
"electron-builder": "^22.9.1"

**Comment by nashaofu** [comment]
已经修复，0.4.1版本不会报错`Error: Cannot find module 'fs/promises'`了

**Comment by Luca-Hsu** [comment]
> 已经修复，0.4.1版本不会报错`Error: Cannot find module 'fs/promises'`了

谢谢，报错已经解决了哈，但打包模糊问题还在 🙏

**Comment by minzhang2** [comment]
mac M1上截出来的图有点糊，不是很高清，这个有解吗

**Comment by xieerduos** [comment]
通过这个代码可以修复 https://github.com/nashaofu/screenshots/issues/245
