### ISSUE TITLE
在 vue-cli-plugin-electron-builder 使用报错

### ISSUE THREAD

**Issue by yuemeng200** [nashaofu/screenshots#122]
大佬您好！我在渲染层直接使用会报错：
> vue.runtime.esm.js?2b0e:1897 TypeError: Screenshots is not a constructor
    at VueComponent.screenShot (App.vue?234e:14)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2188)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6961)

我的`vue.config.js`已经如下配置：
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ["electron-screenshots"],
    },
  },
};
```
在 vue 写法如下：
```js
const Screenshots = require("electron-screenshots");
export default {
  name: "App",
  methods: {
    screenShot() {
      const screenShot = new Screenshots();
      screenShot.startCapture();
      // console.log(Screenshots);
    },
  },
};
```
初次接触electron的小白，麻烦指教！

**Comment by nashaofu** [comment]
请在主进程使用

**Comment by yuemeng200** [comment]
嗯嗯，谢谢您这么快回复我，在主进程可以用。请问为什么有些模块在渲染进程可以用而另一些不可以用，底层的差异是什么呢？

**Comment by yuemeng200** [comment]
> 请在主进程使用



> 请在主进程使用

嗯嗯，谢谢您这么快回复我，在主进程可以用。请问为什么有些模块在渲染进程可以用而另一些不可以用，底层的差异是什么呢？

**Comment by nashaofu** [comment]
同样是js，运行环境不一样啊，所以就不能运行，并且electron就是这样设计的架构，主进程提供API与渲染进程是完全不一样
