### ISSUE TITLE
html 加载错误

### ISSUE THREAD

**Issue by yuemeng200** [nashaofu/screenshots#123]
老哥你好，我尝试在现有的项目中使用你的模块执行`npm run electron:serve`时有如下报错（未引入您的模块时不报错）：
> in ./node_modules/react-screenshots/electron/electron.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <!DOCTYPE html>

能否指教问题的可能来源（来自小实习生的恳求！！！）

**Comment by nashaofu** [comment]
参考：https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#%E6%B3%A8%E6%84%8F
