### ISSUE TITLE
Uncaught (in promise) Error: Cannot read properties of undefined (reading 'getSources')

### ISSUE THREAD

**Issue by chyj4747** [nashaofu/screenshots#124]
electron + vite + vue3

主进程：

    const Screenshots = require('electron-screenshots').default
    app.whenReady().then(() => {
        const screenshots = new Screenshots()
        globalShortcut.register('F2', () => {
            console.log('start capture')
            screenshots.startCapture()
            screenshots.$view.webContents.openDevTools()
        })
    })

![image](https://user-images.githubusercontent.com/6455677/159690523-f77b3c00-4cdf-4f70-bc23-0a3f166bbcf5.png)

**Comment by nashaofu** [comment]
什么版本electron

**Comment by chyj4747** [comment]
> 什么版本electron

17.1.0

**Comment by nashaofu** [comment]
好像17.x API有变更，你可以先用16.x，后面我这边会更新

**Comment by nashaofu** [comment]
发布新版本了，你升级到0.3.0即可
