### ISSUE TITLE
mac 主进程引用打包需要签名

### ISSUE THREAD

**Issue by rhwoodpecker** [nashaofu/screenshots#132]
### version
0.3.1 
### platform
macOS
### question
> mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

是否需要对mac做签名处理，打包之后的mac安装包不能打开，提示 `screenshots` 未签名

**Comment by nashaofu** [comment]
确定是这个包导致的吗？我这边http://github.com/nashaofu/dingtalk是可以打包的？应用初始化的时候最好设置一下app.setAppUserModelId('com.electron.dingtalk')。

**Comment by rhwoodpecker** [comment]
`0.2.0` 版本正常，`0.3.1` 打包运行后主进程提示未签名

**Comment by rhwoodpecker** [comment]
> 确定是这个包导致的吗？我这边[http://github.com/nashaofu/dingtalk](https://github.com/nashaofu/dingtalk) 是可以打包的？应用初始化的时候最好设置一下app.setAppUserModelId('com.electron.dingtalk')。

**Comment by rhwoodpecker** [comment]
### 现象
> 打包后运行提示未签名
<img width="259" alt="image" src="https://user-images.githubusercontent.com/22131908/165275075-d755d629-a2fe-4525-94cd-07e55c4f2f58.png">

### 原因
 在 `0.3.1` 中引用了 `node-screenshots` 依赖包，这个依赖包没有签名
 
![image](https://user-images.githubusercontent.com/22131908/165275538-bfd69d50-6752-43f5-ba9e-858b4b0cc4a8.png)

**Comment by nashaofu** [comment]
你本地直接使用node-screenshots这个包看看可不可以调用呢，你是打包后运行报错哈？我这边打包后的文件运行也没有报错，或者你直接下载这个在本地测试https://github.com/nashaofu/dingtalk/releases/download/v2.1.15/dingtalk-2.1.15-latest-x64.dmg

**Comment by nashaofu** [comment]
https://github.com/electron/osx-sign 看看这个是不是能解决你的问题

**Comment by nashaofu** [comment]
最新版你看看还有这个错误没

**Comment by rhwoodpecker** [comment]
> 最新版你看看还有这个错误没

作者你好，我这测试了下可以了，谢谢
