### ISSUE TITLE
Mac上多屏时，会有问题

### ISSUE THREAD

**Issue by Hin-D** [nashaofu/screenshots#138]
Mac连接外接显示器，然后把应用拖动到外接显示器，触发截图动作，截图界面没有覆盖外接显示器界面，而是显示在屏幕右侧只漏出来一点，感觉是x坐标变成了自身显示器的宽；

electron-screenshots: ^0.4.2
node: v14.18.2
electron: 11.1.1

**Comment by Hin-D** [comment]
另外，触发截图时如何控制界面的颜色，目前的截屏颜色与QQ及微信的截图界面灰度不太一样，用户容易误解

**Comment by w3cways** [comment]
同问：
Windows上也只能截第一屏

**Comment by Hin-D** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/13867945/169767307-4ee23885-f5c6-4f57-b0a6-f9c98367db12.png">

@nashaofu 作者大大你好，这样修改就能处理这个问题，因为没提过RP，作者大大有空就修改了呗~

**Comment by Hin-D** [comment]
0.4.4已处理

**Comment by theores** [comment]
现在仍然有问题啊，windows.

> 0.4.4已处理
