### ISSUE TITLE
0.4.3问题

### ISSUE THREAD

**Issue by Hin-D** [nashaofu/screenshots#139]
1.进入截屏状态，未开始截图时，按Esc无法退出截屏状态；
2.进入截屏状态，开始选中画面，按Esc可以退出截屏状态，但再次进入会有上次的选中框并且不会自动清除；
3.进入截屏状态，开始选中画面，按鼠标右键、X按钮都可以退出截屏状态，但再次进入会有上次的选中框且会自动清除；
4.第一次进入截屏状态时，会有白屏的一下

就第4点，我尝试了以下修改，体验会更好一点；
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/13867945/169777242-96487969-e230-4154-b31a-484b5713fef5.png">

@nashaofu 作者大大有空修改一下呗

**Comment by nashaofu** [comment]
收到，我这边正在尝试修复，【再次进入会有上次的选中框并且不会自动清除】我这边有点难以复现，也有可能是电脑性能不一致，我会尝试修改一些代码

**Comment by Yu-chuancheng** [comment]
1. esc 不能退出
2. 输入文字工具不能使用 ——> 单击后 文字框不获取焦点 且打字无效果 @[nashaofu](https://github.com/nashaofu)

**Comment by Hin-D** [comment]
> 收到，我这边正在尝试修复，【再次进入会有上次的选中框并且不会自动清除】我这边有点难以复现，也有可能是电脑性能不一致，我会尝试修改一些代码

拉最新代码测试了（5月24日），【再次进入会有上次的选中框并且不会自动清除】这个问题不会出现了，但Esc仍然不能退出

**Comment by nashaofu** [comment]
嗯嗯，应该是同一个问题导致

**Comment by nashaofu** [comment]
最新版本看看吧，esc还有点问题，你们先用着吧，我后面再看

**Comment by Hin-D** [comment]
新版本输入的问题OK了

**Comment by nashaofu** [comment]
现在只剩下esc的问题了吧？

**Comment by Hin-D** [comment]
是的，目前已知问题就差Esc无法关闭的

**Comment by Hin-D** [comment]
好吧，刚发现的，右键也无法关闭

**Comment by nashaofu** [comment]
esc 退出截屏始终有些问题，你们这样使用吧！
```js
globalShortcut.register('esc', () => {
  if (screenshots.$win?.isFocused()) {
    screenshots.endCapture()
  }
})
```

**Comment by Hin-D** [comment]
目前Esc退出方案我也是这么做的，刚好我这没使用到esc的快捷键
`screenshots.$win.on('show', (event) => {
            globalShortcut.register('esc', () => {
              if (screenshots.$win && screenshots.$win.isFocused()) {
                screenshots.endCapture()
                globalShortcut.unregister('esc')
              }
            })
          })`
