### ISSUE TITLE
截完图后，程序坞和状态栏没有恢复正常。。需要鼠标移上去才会显示，离开又隐藏了

### ISSUE THREAD

**Issue by iceshou** [nashaofu/screenshots#145]
截图功能可以正常使用。但是截图完之后扩展坞被隐藏了

**Comment by nashaofu** [comment]
最新版本吗？

**Comment by iceshou** [comment]
> 最新版本吗？

对的 @nashaofu

**Comment by nashaofu** [comment]
应该没有问题了，https://github.com/nashaofu/screenshots/commit/899e22ffd68bf04239bb34f987b99e8e969dcbcf
