### ISSUE TITLE
Mac下窗口全屏后，快捷键截图会导致electron崩溃

### ISSUE THREAD

**Issue by w3cways** [nashaofu/screenshots#146]
0.1.2版本不会引起崩溃（不过，快捷键截图后，会导致窗口的信号灯无法显示）

0.4.3 以及最新版本都存在这个问题

**Comment by nashaofu** [comment]
> https://github.com/wildfirechat/vue-pc-chat/tree/master/src/wfc

窗口信号灯是啥？什么系统有这个问题

**Comment by w3cways** [comment]
Mac系统啊
信号灯就是Mac系统上 窗口的关闭、最大化、最小化按钮





------------------ 原始邮件 ------------------
发件人: nashaofu ***@***.***&gt;
发送时间: 2022年6月21日 22:30
收件人: nashaofu/screenshots ***@***.***&gt;
抄送: TonyYuan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[nashaofu/screenshots] Mac下窗口全屏后，快捷键截图会导致electron崩溃 (Issue #146)





  
https://github.com/wildfirechat/vue-pc-chat/tree/master/src/wfc
  
窗口信号灯是啥？什么系统有这个问题

**Comment by nashaofu** [comment]
你clone一下[这个仓库](https://github.com/nashaofu/electron-screenshots-issue)在本地运行试试，看看是否会有这个问题。

**Comment by w3cways** [comment]
> 你clone一下[这个仓库](https://github.com/nashaofu/electron-screenshots-issue)在本地运行试试，看看是否会有这个问题。

我提交了一个pr ,你合并后看下，是能复现问题 的

启动后，窗口最大化，然后再快捷键截图，electron崩溃。退出

**Comment by nashaofu** [comment]
electron 的bug，我已经提交了issue，https://github.com/electron/electron/issues/34704，我这边也会尝试，看能不能再项目中修复

**Comment by nashaofu** [comment]
更新了一个版本，崩溃问题应该不存在了

**Comment by w3cways** [comment]
> 更新了一个版本，崩溃问题应该不存在了

崩溃问题没了，不过还有另外一个问题，全屏截图完成后，没有恢复到全屏的窗口，此问题先关闭了

**Comment by ZWhitey** [comment]
> 更新了一个版本，崩溃问题应该不存在了
你好，我用了 v0.5.6 還是會有遇到崩潰的問題，也有測試過 [electron-screenshots-issue](https://github.com/nashaofu/electron-screenshots-issue) 都是一樣會遇到跟[這邊](https://github.com/electron/electron/issues/34704)一樣的錯誤。
```
2022-07-12 15:02:47.303 Electron[13383:7695362] -[NativeWidgetMacNSWindowBorderlessFrame _surrenderToolbarViewForFullScreenWindow]: unrecognized selector sent to instance 0x135fc2a00
```

**Comment by nashaofu** [comment]
你是用这个测试一下呢，https://github.com/nashaofu/electron-screenshots-issue/tree/0.5.6, 我这边是正常工作的，没有崩溃。

**Comment by ZWhitey** [comment]
> 你用这个测试一下呢，https://github.com/nashaofu/electron-screenshots-issue/tree/0.5.6, 我这边是正常工作的，没有崩溃。

我現在測試 0.5.6 的 tag 沒有問題，但是在我自己的使用環境還是會崩潰。
我在猜是 electron 版本的問題，所以我測試把你的 electron 降級到跟我的環境一樣 13.6.9 就會崩潰了，要再請你看一下問題在哪邊。

**Comment by nashaofu** [comment]
你把 electron 升级到14吧！13.6.9 确实会出现这个问题。我这边不容易修复这个问题。

**Comment by ZWhitey** [comment]
感謝你的幫忙，我升級完可以正常使用了，不過有遇到另外的問題，我再開一個 issue 給你。

**Comment by lynn6020** [comment]
请问问题是怎么解决的呢，我的electron版本是14.2.9 ，electron-screenshots版本0.5.14 ，还是会复现这个问题
