### ISSUE TITLE
windows浏览器和electron应用端，截图会有抖动

### ISSUE THREAD

**Issue by S112** [nashaofu/screenshots#151]
https://user-images.githubusercontent.com/7778864/176830428-d77d52fe-76e3-4b91-9917-af154bc0f9db.mp4

你好，
windows浏览器和electron应用端，截图会有抖动的问题。
mac是正常的，麻烦看一下这个问题吧。

**Comment by nashaofu** [comment]
发了最新版，你看看

**Comment by nashaofu** [comment]
在浏览器打开这个页面吗？https://github.com/nashaofu/screenshots，我这边没有复现出来

**Comment by S112** [comment]
是的，是windows 浏览器端。
本地跑 react-screenshots 项目，发现的。 
0.5.8版本

**Comment by S112** [comment]
> 在浏览器打开这个页面吗？[https://github.com/nashaofu/screenshots，我这边没有复现出来](https://github.com/nashaofu/screenshots%EF%BC%8C%E6%88%91%E8%BF%99%E8%BE%B9%E6%B2%A1%E6%9C%89%E5%A4%8D%E7%8E%B0%E5%87%BA%E6%9D%A5)

你好，这个问题，在看吗？
什么时候能修复呢？
我们的electron桌面应用就是用的这个插件，用户一直在用。

**Comment by S112** [comment]
> 在浏览器打开这个页面吗？[https://github.com/nashaofu/screenshots，我这边没有复现出来](https://github.com/nashaofu/screenshots%EF%BC%8C%E6%88%91%E8%BF%99%E8%BE%B9%E6%B2%A1%E6%9C%89%E5%A4%8D%E7%8E%B0%E5%87%BA%E6%9D%A5)

我重新录制了，windows端浏览器，官方demo。

https://user-images.githubusercontent.com/7778864/181426118-843f6857-fe70-40b2-9f75-e5a60fac7497.mp4

**Comment by nashaofu** [comment]
我这边复现不了

**Comment by nashaofu** [comment]
我复现了，缩放屏幕后会出现

**Comment by nashaofu** [comment]
发了新版本了，你再试试

**Comment by S112** [comment]
> 

浏览器端可以了，
但是electron里还是不行，是因为 will-change 这个属性，在electron中不生效吗？

**Comment by S112** [comment]
> 发了新版本了，你再试试

浏览器端可以了，
但是electron里还是不行，是因为 will-change 这个属性，在electron中不生效吗？

**Comment by nashaofu** [comment]
还是出现白条是吗？我周末再看看

2022年8月11日 10:50，S112 ***@***.******@***.***>> 写道：



发了新版本了，你再试试

浏览器端可以了，
但是electron里还是不行，是因为 will-change 这个属性，在electron中不生效吗？

**Comment by nashaofu** [comment]
没有复现出来
