### ISSUE TITLE
0.5.2版本，linux使用nodeScreenshots所有静态方法都会闪退

### ISSUE THREAD

**Issue by peekabooovo** [nashaofu/screenshots#153]
**Describe the bug**

**To Reproduce**
**linux单屏截图调用nodeScreenshot**

**Versions (please complete the following information):**
 - OS:linux
 - Electron17.4.3
 - electron-screenshots 0.5.4

**Comment by peekabooovo** [comment]
Stack trace of thread 24319:
                #0  0x00007fdb5e062ce4 n/a (node-screenshots.linux-x64-gnu.node)
                #1  0x00007fdb5e07e546 n/a (node-screenshots.linux-x64-gnu.node)
                #2  0x00007fdb5e058596 n/a (node-screenshots.linux-x64-gnu.node)
                #3  0x000055782c2de52b n/a (electron)
                #4  0x0000557826f4773b n/a (electron)
                #5  0x000027d407f0a878 n/a (n/a)
                #6  0x000027d407e8c6a2 n/a (n/a)
                #7  0x000027d4000ca2f4 n/a (n/a)
                #8  0x000027d4000c803e n/a (n/a)
                #9  0x000027d4000aba1f n/a (n/a)
                #10 0x000027d4000b73b7 n/a (n/a)
                #11 0x000027d407e8a6dc n/a (n/a)
                #12 0x000027d407e8a407 n/a (n/a)
                #13 0x0000557827007068 n/a (electron)
                #14 0x00005578270064aa _ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_iPS6_ (electron)
                #15 0x0000557826efa9dc _ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_ (electron)
                #16 0x000055782c273e57 n/a (electron)
                #17 0x000055782c274173 _ZN4node12MakeCallbackEPN2v87IsolateENS0_5LocalINS0_6ObjectEEENS3_INS0_8FunctionEEEiPNS3_INS0_5ValueEEENS_13async_contextE (electron)
                #18 0x0000557825fd8add n/a (electron)
                #19 0x0000557825f3455d n/a (electron)
                #20 0x0000557825f213bd n/a (electron)
                #21 0x0000557825f2149c n/a (electron)
                #22 0x0000557825f53760 n/a (electron)
                #23 0x0000557828874a44 n/a (electron)
                #24 0x0000557825f53b0b n/a (electron)
                #25 0x0000557828e01738 n/a (electron)
                #26 0x0000557828e069ac n/a (electron)
                #27 0x0000557828e02c7a n/a (electron)
                #28 0x0000557829027721 n/a (electron)
                #29 0x0000557828e03d3f n/a (electron)
                #30 0x0000557828acb4c6 n/a (electron)
                #31 0x0000557828ae727d n/a (electron)
                #32 0x0000557828a96caf n/a (electron)
                #33 0x00007fdb734f867d g_main_context_dispatch (libglib-2.0.so.0)
                #34 0x00007fdb734f8a48 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                #35 0x00007fdb734f8ae0 g_main_context_iteration (libglib-2.0.so.0)
                #36 0x0000557828a9699b n/a (electron)
                #37 0x0000557828ae7c04 n/a (electron)
                #38 0x0000557828ab498c n/a (electron)
                #39 0x0000557827dea8cf n/a (electron)
                #40 0x0000557827dec452 n/a (electron)
                #41 0x0000557827de80ae n/a (electron)
                #42 0x0000557826117af1 n/a (electron)
                #43 0x0000557826118f58 n/a (electron)
                #44 0x000055782611892b n/a (electron)
                #45 0x0000557826115e6e n/a (electron)
                #46 0x0000557826116883 n/a (electron)
                #47 0x0000557825ea8b48 n/a (electron)
                #48 0x00007fdb6e447873 __libc_start_main (libc.so.6)
                #49 0x0000557825b0202a _start (electron)
从闪退堆栈只能看出闪退在node-screenshots.linux-x64-gnu.node，看不出有用信息

**Comment by nashaofu** [comment]
你是linux什么发行版呀？

**Comment by bruceauyeung** [comment]
[      let crtc_info = *crtc_info_ptr;](https://github.com/nashaofu/display-info/blob/a8a344bc29b4bff56b810d58067746f6d7033e73/src/linux.rs#L94)

是这里指针为空导致的。 for循环能迭代2次，第二次时这里指针为空了。加了为空判断后就好了
你是linux什么发行版呀？ ---- 一个自己修改的发行版。

**Comment by nashaofu** [comment]
> [ let crtc_info = *crtc_info_ptr;](https://github.com/nashaofu/display-info/blob/a8a344bc29b4bff56b810d58067746f6d7033e73/src/linux.rs#L94)
> 
> 是这里指针为空导致的。 for循环能迭代2次，第二次时这里指针为空了。加了为空判断后continue就好了 你是linux什么发行版呀？ ---- 一个自己修改的发行版，跑在kvm虚机里面。 你今天能修复完吗？能的话我就等你的改动，不然我本地先打补丁了。 @nashaofu

已经发新版本了，看看是否修复

**Comment by bruceauyeung** [comment]
> > [ let crtc_info = *crtc_info_ptr;](https://github.com/nashaofu/display-info/blob/a8a344bc29b4bff56b810d58067746f6d7033e73/src/linux.rs#L94)
> > 是这里指针为空导致的。 for循环能迭代2次，第二次时这里指针为空了。加了为空判断后continue就好了 你是linux什么发行版呀？ ---- 一个自己修改的发行版，跑在kvm虚机里面。 你今天能修复完吗？能的话我就等你的改动，不然我本地先打补丁了。 @nashaofu
> 
> 已经发新版本了，看看是否修复

感谢快速响应！赞！
我看了你在display_info的修改，应该是可以的。晚些时候验证。
提个建议：编译时能留下函数名这些符号吗？目前crash的时候，coredump里面函数名的地方只能看到 n/a，非常不利于快速定位闪退位置。

**Comment by nashaofu** [comment]
> > > [ let crtc_info = *crtc_info_ptr;](https://github.com/nashaofu/display-info/blob/a8a344bc29b4bff56b810d58067746f6d7033e73/src/linux.rs#L94)
> > > 是这里指针为空导致的。 for循环能迭代2次，第二次时这里指针为空了。加了为空判断后continue就好了 你是linux什么发行版呀？ ---- 一个自己修改的发行版，跑在kvm虚机里面。 你今天能修复完吗？能的话我就等你的改动，不然我本地先打补丁了。 @nashaofu
> > 
> > 
> > 已经发新版本了，看看是否修复
> 
> 感谢快速响应！赞！ 我看了你在display_info的修改，应该是可以的。晚些时候验证。 提个建议：编译时能留下函数名这些符号吗？目前crash的时候，coredump里面函数名的地方只能看到 n/a，非常不利于快速定位闪退位置。
不保留是因为想减少包的大小，不然生成文件有点大
