### ISSUE TITLE
Mac 全屏下截圖後 screenshots 視窗並沒有關閉

### ISSUE THREAD

**Issue by ZWhitey** [nashaofu/screenshots#155]
**Describe the bug**
Mac 全屏下截圖後 screenshots 視窗並沒有關閉，而是隱形擋在原本的視窗上面造成無法使用，上方的狀態列也無法正常顯示

**To Reproduce**
1. 開啟 electron
2. 放到全屏
3. 截圖
4. 原本的畫面無法點擊

**Reproduce repository**
You can fork the repository below to test
https://github.com/nashaofu/electron-screenshots-issue

**Expected behavior**
能夠正常操作

**Screenshots**
截圖後左上角會出現隱形視窗的按鈕，點 X 後雖然可以繼續操作，但是上方 mac 狀態列出不來，也無法再次縮小
![image](https://user-images.githubusercontent.com/11453697/178938502-41c24ca5-d131-452e-b5be-c9a8b71fe8af.png)

**Versions (please complete the following information):**
 - OS: macOS 12.4
 - Electron: 19.0.5
 - electron-screenshots: 0.5.6

**Additional context**
如果截圖多次 screenshots 會越來越多 (不開全屏也會有一樣的問題)
![image](https://user-images.githubusercontent.com/11453697/178939928-64195d9b-5e59-4235-abb3-3178964b4380.png)

**Comment by nashaofu** [comment]
发布新版本了

**Comment by ZWhitey** [comment]
> 发布新版本了

感謝你這麼快就修復完，我測試新版還有一個問題是截圖完上方的狀態列就不會顯示出來了，必須要用鍵盤切到其他地方再回來才能正常顯示。

截圖前、切畫面後回來才可以正常顯示，截圖過後就沒有了。
![image](https://user-images.githubusercontent.com/11453697/179166790-2ddfc49c-e305-4fbd-a23d-3e8f3b15ae04.png)
