### ISSUE TITLE
关于windows下修改缩放比例之后截图模糊抖动的问题

### ISSUE THREAD

**Issue by zifeiyu666** [nashaofu/screenshots#158]
您好，我在使用的时候发现一个问题。再windows下如果缩放比例使用的不是100%，而是大于100%的话，截图的时候整个窗口都会变模糊，而且截图框拖动的时候会抖动。这个问题是什么原因导致的？可以解决么？万分感谢。

**Comment by nashaofu** [comment]
后面有时间我看看哈

**Comment by nashaofu** [comment]
升级最新版试试
