### ISSUE TITLE
升级到最新版本，截图遮罩没有了吗？

### ISSUE THREAD

**Issue by a350719840** [nashaofu/screenshots#159]
**Describe the bug**

**To Reproduce**

**Reproduce repository**
You can fork the repository below to test
https://github.com/nashaofu/electron-screenshots-issue

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Electron [e.g. 16.0.0]
 - electron-screenshots [e.g. 0.5.0]

**Additional context**

**Comment by nashaofu** [comment]
我发了最新版本，你看看，应该是一直都有的
