### ISSUE TITLE
Mac下打包的时候报错

### ISSUE THREAD

**Issue by iceshou** [nashaofu/screenshots#166]
"issues": [
    {
      "severity": "error",
      "code": null,
      "path": "xxxx/Contents/Resources/app/node_modules/node-screenshots/.yarn/cache/fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip/node_modules/fsevents/fsevents.node",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "xxxx//Contents/Resources/app/node_modules/node-screenshots/.yarn/cache/fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip/node_modules/fsevents/fsevents.node",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "xxxx//Contents/Resources/app/node_modules/node-screenshots/.yarn/cache/fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip/node_modules/fsevents/fsevents.node",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "xxxx/Contents/Resources/app/node_modules/node-screenshots/.yarn/cache/fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip/node_modules/fsevents/fsevents.node",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    }
  ]

**Comment by nashaofu** [comment]
新版本看看是否解决了呢
