### ISSUE TITLE
mac截图时只显示当前应用窗口

### ISSUE THREAD

**Issue by minzhang2** [nashaofu/screenshots#170]
开始截图时其他应用的窗口、程序坞都被关闭了，这个是什么原因，可以做到不关闭吗

**Comment by nashaofu** [comment]
mac要做截图授权，否则就是这个情况，在程序中添加如下代码，保证系统能授权。
```js
app.setAppUserModelId('com.electron.dingtalk')
```

**Comment by minzhang2** [comment]
我加了这个，在本地跑起来是其他窗口依然被关闭，没有唤起授权的窗口，需要prod的包才会生效吗

**Comment by nashaofu** [comment]
本地跑的时候，要授权 vscode 或者终端程序权限，因为你的程序是由终端拉起来的
