### ISSUE TITLE
electron 21.x.x V8 sandboxed pointers 和 V8 Memory Cage

### ISSUE THREAD

**Issue by mlmdflr** [nashaofu/screenshots#172]
![image](https://user-images.githubusercontent.com/93173537/195114956-455d8b67-c486-4a9c-90ac-5818c1d613d3.png)

详细可见

https://www.electronjs.org/blog/electron-21-0#breaking--api-changes

**Comment by mlmdflr** [comment]
大佬有无更好的解决方案

**Comment by nashaofu** [comment]
https://github.com/napi-rs/napi-rs/issues/1346

**Comment by mlmdflr** [comment]
还没啥好的解决方案吗

**Comment by nashaofu** [comment]
目前先使用electron 的方式截图，不过性能与清晰度可能不是很好，你可以升级插件版本看看，这个问题我这边长期跟进

**Comment by nashaofu** [comment]
已经解决这个问题啦
