### ISSUE TITLE
windows下截图，大概有2s左右的延迟反应时间。

### ISSUE THREAD

**Issue by lynn6020** [nashaofu/screenshots#183]
window下调用截图插件，有2s左右的截图延迟时间，使用版本为0.5.14

**Comment by lynn6020** [comment]
electron 项目~原因是desktopCapturer.getSources 会导致整个程序挂起，会导致部分电脑卡顿？

**Comment by lynn6020** [comment]
想请教下大佬，有没有好的解决方案，，，，

**Comment by nashaofu** [comment]
我这边截图比较快，而且默认不是使用desktopCapturer.getSources进行截图的

**Comment by lynn6020** [comment]
已解决

**Comment by theores** [comment]
> 已解决

请问怎么解决的啊，我到现在还是有延迟。
