### ISSUE TITLE
打包后找不到 screenshots

### ISSUE THREAD

**Issue by yurnery** [nashaofu/screenshots#184]
主进程是用的 webpack 打包的, 按照说明文档在 webpack 也加入了external 配置, 打完包后一启动还是报错找不到相关依赖. 应该怎么解决呢? 请大佬告知

webpack 配置:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/16872556/208802574-7718c50e-dd7e-4d1f-aa44-6fc6153616ff.png">

报错截图:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16872556/208802860-131135e8-9b0a-4f1a-a5f0-236c64861215.png">

**Comment by yurnery** [comment]
使用的是 pnpm, 跟这个有关系吗

**Comment by nashaofu** [comment]
你用其他的依赖管理工具试试呢？pnpm好像都是使用全局缓存的

**Comment by yurnery** [comment]
确实是 pnpm 的问题, 在 electron-builder官网找到解决方案了, https://www.electron.build/index.html#note-for-pnpm

**Comment by yurnery** [comment]
但是依赖的node-screenshots 这个库, 在 M1上打universal 的包的时候会报错, xxx have the same architectures (arm64) and can't be in the same fat output file.
