### ISSUE TITLE
electron-webpack-typescript打包求助

### ISSUE THREAD

**Issue by Riceneeder** [nashaofu/screenshots#189]
### 我使用electron-forge生成的项目，根据readme调整webpack配置文件 ``'electron-screenshots': 'require("electron-screenshots")'`` ，但在开发环境和打包后都会出现以下错误

![image](https://user-images.githubusercontent.com/86492950/210213613-1d5eae4e-3795-4bda-92b9-8651f1e79ca9.png)

### 修改为 ``'electron-screenshots': "electron-screenshots"`` 后开发环境能正常运行，但打包后会出现以下错误

![image](https://user-images.githubusercontent.com/86492950/210214043-5de4c6e2-897d-46be-ada2-09f15071bdca.png)

### 只有在打包后将以下包手动复制到 ``resources/app/node_modules`` 下后程序才能正常运行
```
      "electron-screenshots",
      "debug",
      "fs-extra",
      "graceful-fs",
      'jsonfile',
      'ms',
      "react-screenshots",
      "universalify"
```

## webpack.main.config
```
import type { Configuration } from 'webpack';
import { rules } from './webpack.rules';
export const mainConfig: Configuration = {
  entry: './src/index.ts',
  module: {
    rules,
  },
  resolve: {
    extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
  },
  externals:{
    'electron-screenshots': "electron-screenshots"
  },
};
```

## webpack.rules
```
import type { ModuleOptions } from 'webpack';

export const rules: Required<ModuleOptions>['rules'] = [
  {
    test: /native_modules[/\\].+\.node$/,
    use: 'node-loader',
  },
  {
    test: /[/\\]node_modules[/\\].+\.(m?js|node)$/,
    parser: { amd: false },
    use: {
      loader: '@vercel/webpack-asset-relocator-loader',
      options: {
        outputAssetBase: 'native_modules',
      },
    },
  },
  {
    test: /\.tsx?$/,
    exclude: /(node_modules|\.webpack)/,
    use: {
      loader: 'ts-loader',
      options: {
        transpileOnly: true,
      },
    },
  },
];
```

# 希望得到帮助，谢谢❤

**Comment by Riceneeder** [comment]
已解决

**Comment by DZwangbing** [comment]
> 已解决

@Riceneeder 请问如何处理的呀

**Comment by Riceneeder** [comment]
> > 已解决
> 
> 
> 
> @Riceneeder 请问如何处理的呀

忘记了，当时的仓库都删了，如果这个库实在打包不了，可以试试原生api ，参考https://segmentfault.com/a/1190000011511358

**Comment by DZwangbing** [comment]
> > > 已解决
> > 
> > 
> > @Riceneeder 请问如何处理的呀
> 
> 忘记了，当时的仓库都删了，如果这个库实在打包不了，可以试试原生api ，参考https://segmentfault.com/a/1190000011511358

@Riceneeder 好的 thx
