### ISSUE TITLE
当截图开始后必须进行截图，否侧无法从截图页面出去

### ISSUE THREAD

**Issue by szz19960815** [nashaofu/screenshots#19]
希望可以新增一个destroy方法，能够使用esc之类的快捷键直接进行取消截图
![微信截图_20190828115702](https://user-images.githubusercontent.com/34050538/63824804-fe433d00-c98a-11e9-8ba8-7adc86c0497d.png)

**Comment by nashaofu** [comment]
好的

**Comment by nicksun011** [comment]
调用destroy报错，TypeError: shortcutCapture.destroy is not a function

**Comment by bruceauyeung** [comment]
@nicksun011 not implemented yet.

**Comment by nicksun011** [comment]
不好意思，看错了，以为是实现了的

**Comment by nashaofu** [comment]
你可以使用新版本的electron-screenshots试试，electron-screenshots是shortcut-capture的替代版本，新版本可以使用`endCapture`方法结束截图，具体可参考：https://github.com/nashaofu/screenshots/tree/master/packages/electron-screenshots#readme

**Comment by bruceauyeung** [comment]
@nashaofu electron-screenshots 是不是就是你说的 shortcut-capture 的重写版本？ shortcut-capture 后续还继续维护吗？

**Comment by nashaofu** [comment]
@bruceauyeung  shortcut-capture后面不维护了，shortcut-capture可直接替换为shortcut-capture，升级过程改动很小
