### ISSUE TITLE
关闭截图进程

### ISSUE THREAD

**Issue by caipenga** [nashaofu/screenshots#2]

**Comment by caipenga** [comment]
执行 app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})， 截图的进程还一直在后台运行，结束不掉

**Comment by nashaofu** [comment]
已经添加destroy方法，该方法可以销毁截图进程。window-all-closed事件应该是不能正常执行的，因为截图进程的窗口会一直存在。你可以通过托盘菜单退出点击执行如下函数的方式进行退出应用
```js
  /**
   * 退出应用
   */
  quit () {
    this.$shortcutCapture.destroy()
    BrowserWindow.getAllWindows().forEach(item => {
      if (!item.isDestroyed()) item.destroy()
    })
    if (process.platform !== 'darwin') {
      if (this.$tray && !this.$tray.isDestroyed()) {
        this.$tray.destroy()
        this.$tray = null
      }
      app.quit()
    }
  }
```
可参考：https://github.com/nashaofu/dingtalk/blob/dev/src/main/dingtalk.js#L116
