### ISSUE TITLE
react-screenshots 0.5.16 版本缺少文件

### ISSUE THREAD

**Issue by ggymm** [nashaofu/screenshots#200]
**Describe the bug**

**To Reproduce**

**Reproduce repository**
You can fork the repository below to test
https://github.com/nashaofu/electron-screenshots-issue

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/20694755/220880307-195fdd3b-6816-4c61-bb29-4155f789307e.png)

![image](https://user-images.githubusercontent.com/20694755/220880374-9c43ab1c-23c4-46da-8552-ead374c94489.png)

![image](https://user-images.githubusercontent.com/20694755/220880461-732da714-026f-46cc-9e7e-398297a2e797.png)

**Versions (please complete the following information):**
 - Electron [e.g. 16.0.0]
 - electron-screenshots [e.g. 0.5.0]

**Additional context**

**Comment by nashaofu** [comment]
已经修复
