### ISSUE TITLE
Invalid hook call. You might have mismatching versions of React and the renderer

### ISSUE THREAD

**Issue by Chandan-TY** [nashaofu/screenshots#201]
We are using React version 18.1.0 along with the electron app. While we tried installing electron-screenshots and using them. We are getting an Invalid hook call. You might have mismatching versions of React and the renderer. 
I can see in node_modules\electron-screenshots\node_modules\react-screenshots the react version is 17.0.2. I think the issue is because of that. Let us know what is the fix for this issue. 

![image](https://user-images.githubusercontent.com/55542021/220904463-affca154-244e-4a28-adfd-1c3f75e48451.png)

1. Create an electron app with react 18 version and versions as specified below
2. Install electron-screenshots
3. Run the app 
4. See the error

Expected behavior
Should support React version 18 also 

![image](https://user-images.githubusercontent.com/55542021/220905022-7e466004-8291-4ebf-934d-daa64817c85b.png)

Versions:
 - React : 
     "react": "^18.1.0",
    "react-dom": "^18.1.0",
 - Electron: "electron": "^16.0.5",
 - electron-screenshots: "electron-screenshots": "^0.5.15",

**Comment by Chandan-TY** [comment]
@nashaofu 
Could you please guide me on fixing the above issue

**Comment by nashaofu** [comment]
Do you have a recurrence code? Do you want to use the electric screenshot? Can the following code work normally?
```ts
import { app, globalShortcut } from 'electron'
import Screenshots from './screenshots'

app.whenReady().then(() => {
  const screenshots = new Screenshots()
  globalShortcut.register('ctrl+shift+a', () => {
    screenshots.startCapture()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

**Comment by Chandan-TY** [comment]
The issue is resolved after adding 
alias: {
      react: path.resolve('./node_modules/react'),
    }
    inside resolve object in webpack.config.js.
