### ISSUE TITLE
在electron-vite里使用无法使用

### ISSUE THREAD

**Issue by MrSteins** [nashaofu/screenshots#217]
在app.whenReady中初始化
<img width="369" alt="截屏2023-06-06 16 27 46" src="https://github.com/nashaofu/screenshots/assets/66707682/cf42e575-8041-4434-9004-58b2b7150017">
无法弹窗，是否需要修改vite配置

**Versions (please complete the following information):**
 - OS: [MACOS 13 M1]
 - Electron [21.4.4]
 - electron-screenshots [0.5.22]

**Additional context**

**Comment by nashaofu** [comment]
有报错信息吗？

**Comment by MrSteins** [comment]
导入的Screenshots需要加default, 是否是因为打包导出的esm导致？

**Comment by MrSteins** [comment]
<img width="304" alt="截屏2023-06-15 23 10 02" src="https://github.com/nashaofu/screenshots/assets/66707682/dbc3cd79-119e-426b-8297-557e4a319c27">
这样使用就正常

**Comment by jjeejj** [comment]
有解决吗？
现在在 electron-vite 使用 会提示 `UnhandledPromiseRejectionWarning: TypeError: Screenshots is not a constructor`
实际上是有这个class的
<img width="607" alt="image" src="https://github.com/nashaofu/screenshots/assets/15176971/53cfc4a5-3461-454e-a4da-adcab762f6e1">

**Comment by xyangst** [comment]
@jjeejj  it still works if you do Screenshots.default, but it doesnt match up with the types

**Comment by nashaofu** [comment]
Already fixed
