### ISSUE TITLE
能支持windows端跨屏载图吗

### ISSUE THREAD

**Issue by jsqq520** [nashaofu/screenshots#227]
**Describe the bug**

**To Reproduce**

**Reproduce repository**
You can fork the repository below to test
https://github.com/nashaofu/electron-screenshots-issue

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Electron [e.g. 16.0.0]
 - electron-screenshots [e.g. 0.5.0]

**Additional context**

**Comment by nashaofu** [comment]
目前不能支持
