### ISSUE TITLE
工具条怎么呼出呢

### ISSUE THREAD

**Issue by nicksun011** [nashaofu/screenshots#23]

**Comment by nashaofu** [comment]
需要拖拽截图了之后才会显示工具条

**Comment by nicksun011** [comment]
按例子引入，截图后只有关闭和确定，没有编辑那些功能，是拿掉了？

**Comment by nashaofu** [comment]
你可以使用新版本的electron-screenshots试试，electron-screenshots是shortcut-capture的替代版本

**Comment by nicksun011** [comment]
用了新的electron-screenshots已经看到工具栏了。多谢。
发现一个问题，就是在windows高分屏上，截图后模糊。

**Comment by nashaofu** [comment]
是有这个问题

**Comment by dpp050700** [comment]
@nashaofu 您好 钉钉那个项目里面的还没更新吗？我看到工具条只有 叉 和 勾

**Comment by jackiewillen** [comment]
> 用了新的electron-screenshots已经看到工具栏了。多谢。
> 发现一个问题，就是在windows高分屏上，截图后模糊。

在高分辨率的mac os上也存在这个问题。按下快捷键呼起截图冻结桌面的时候，冻结的页面的分辨率明显下降了。这个可以在代码哪边设置吗？

**Comment by nashaofu** [comment]
> @nashaofu 您好 钉钉那个项目里面的还没更新吗？我看到工具条只有 叉 和 勾

那边最新版已经更新了的
