### ISSUE TITLE
升级到0.5.24（及以上）后报错：UnhandledPromiseRejectionWarning: TypeError: Screenshots is not a constructor

### ISSUE THREAD

**Issue by joyexpr** [nashaofu/screenshots#232]
由0.5.23升级到0.5.24后，执行 screenshots = new Screenshots({ singleWindow: true }) 就开始报错

UnhandledPromiseRejectionWarning: TypeError: Screenshots is not a constructor

**Comment by nashaofu** [comment]
可以打印下 Screenshots 吗？看起来是 Screenshots 对

**Comment by joyexpr** [comment]
现在可以了，把引入方式调整了下，原先是
const Screenshots = require('electron-screenshots').default

改成
import Screenshots from 'electron-screenshots'
