### ISSUE TITLE
成功回调screenshots.on会随着裁切的次数进行累积的触发

### ISSUE THREAD

**Issue by changbb** [nashaofu/screenshots#237]
**Describe the bug**
成功回调screenshots.on会随着裁切的次数进行累积的触发，裁切第一次触发一次，再进行拆迁会连续触发2次
录屏：
https://github.com/nashaofu/screenshots/assets/23628509/a2944ae3-f255-49aa-87bc-71026b1df548

代码截图：

![image](https://github.com/nashaofu/screenshots/assets/23628509/5d5a9e51-91a1-43c2-89fb-f98cb43c3aa6)
![image](https://github.com/nashaofu/screenshots/assets/23628509/be2490e0-c91a-4170-a7d2-3d68e5e6b2ed)

**Versions (please complete the following information):**
 - OS: windows
 "electron": "^20.3.12",
 "electron-screenshots": "^0.5.26",
 "vue-electron": "^1.0.6",

**Comment by nashaofu** [comment]
假期有时间看一下

**Comment by changbb** [comment]
> 假期有时间看一下

感谢回复，我现在可以确定的是造成这个的原因是通过ipcMain.on监听造成的
`    ipcMain.on('take-screenshot', (event) => {
        screenshots.startCapture()
    });`

我是想通过渲染进程触发 screenshots.startCapture()，然后再监听“ok”事件
`screenshots.on("ok", (e, buffer, bounds) => {
        mainWindow.webContents.send('screenshot-result', buffer);
    });`
把结果传递给渲染进程进行处理，这样就造成了会累加多次触发ok事件

**Comment by changbb** [comment]
原因找到了吗，但是通过渲染进程take-screenshot造成的累加触发还是想不到解决方案

**Comment by changbb** [comment]
> 假期有时间看一下

已经解决是因为我把this.$electron.ipcRenderer.on('screenshot-result', (event, image) => {}） 监听事件写在触发方法里面了
