### ISSUE TITLE
使用提供的esc 关闭截图方法后，其余应用程序esc 都失效了

### ISSUE THREAD

**Issue by list12318** [nashaofu/screenshots#239]
![image](https://github.com/nashaofu/screenshots/assets/33713614/626c0302-0d3c-4a8a-b149-0855bec18625)

使用提供的esc方法后，微信，QQ的esc最小化应用程序键都失效了，无法最小化

**Comment by nashaofu** [comment]
这个是你自己注册了全局快捷键
