### ISSUE TITLE
某下Windows桌面下截图出现严重颜色失真

### ISSUE THREAD

**Issue by yykoypj** [nashaofu/screenshots#246]
使用最新版本的截图库，在一台windows上出现下图这种（windows事件管理器）文字颜色丢失的问题，
截图之后的全屏页面展示是正常的，
扩选部分截图（screenshots-canvas-panel）或者通过鼠标右下方的小预览窗口（screenshots-magnifier-body-canvas）看到的就有问题
看代码像是canvas.drawImage导致的问题，但是不知道如何解决，别的电脑也无法复现
<img width="580" alt="image" src="https://github.com/user-attachments/assets/7cb9a7e1-3a4c-4da6-853a-43ac3ee13339">

**Comment by nashaofu** [comment]
windows事件管理器是吧？应该底层截图有问题，我看看

**Comment by yykoypj** [comment]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/3062c9c8-737d-4cfe-8cfb-9bdc3194ba99">
看这张图更清楚一点，感觉不像底层截图的问题

**Comment by nashaofu** [comment]
用node-screenshots截图试试呢

**Comment by yykoypj** [comment]
我更新到新版就可以了，貌似是这个地方解决了
 https://github.com/nashaofu/xcap/pull/93/commits/4f568dbb5a148b85faa2569d21ea7c3ca7da5197
