### ISSUE TITLE
我在主进程里面引入const Screenshots = require('electron-screenshots')；下面new Screenshots()报错了，说Screenshots不是一个constructor

### ISSUE THREAD

**Issue by zhoutangyan** [nashaofu/screenshots#29]

**Comment by nashaofu** [comment]
使用`const Screenshots = require('electron-screenshots').default`

**Comment by zhoutangyan** [comment]
哦哦，可以了，谢谢；还有一个问题就是，如果在1920*1080分辨率的电脑上，一般电脑显示都是150%,这种时候截取的图片就会失真了，不知道绘制的时候能不能加上window.devicePixelRatio之类的

**Comment by nashaofu** [comment]
发布新版本了，支持高分屏了
