### ISSUE TITLE
electron-vue-cli4整合启动就报错

### ISSUE THREAD

**Issue by fjl280855990** [nashaofu/screenshots#31]
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>react-screenshots</title><link href="css/app.b8133b05447b55a381ce.css" rel="stylesheet"></head><body><nosc
ript><strong>很抱歉，没有JavaScript，网站不能正常工作。请启用JavaScript。</strong></noscript><div id="app"></div><script src="js/app.ba516492ce39f1719cc8.js"></script></body></html>

**Comment by nashaofu** [comment]
能提供更详细的信息吗？electron-vue-cli4是指https://github.com/nklayman/vue-cli-plugin-electron-builder这个吗？

**Comment by fjl280855990** [comment]
应该是解析作者编译后的index.html文件里边的css、js的问题，缺少对webpack配置，应该是这个意思，只是我不知道咋配置。。。

**Comment by nashaofu** [comment]
index.html为啥还要经过webpack呢，请在主进程中调用本插件

**Comment by fjl280855990** [comment]
我在主程序new了之后，程序就报这个错，启都起不了

**Comment by nashaofu** [comment]
你检查一下你cli的配置吧，一般项目主进程只需要bable-loader就好了，不需要其他的loader

**Comment by fjl280855990** [comment]
启动的时候需要编译
![1](https://user-images.githubusercontent.com/35919845/78848832-773c6400-7a45-11ea-912d-182ebcc0524b.png)
![2](https://user-images.githubusercontent.com/35919845/78848835-786d9100-7a45-11ea-8c21-e04030ab843e.png)

**Comment by nashaofu** [comment]
```js
{
  externals: {
    'electron-screenshots': 'require("electron-screenshots")'
  }
}
```
webpack配置一下这个

**Comment by fjl280855990** [comment]
这个也是有的

**Comment by nashaofu** [comment]
你输出最终配置看看吧，都排除了的不打包的东西，应该是不会再经过webpack处理的

**Comment by fjl280855990** [comment]
![6](https://user-images.githubusercontent.com/35919845/78849609-87554300-7a47-11ea-99f6-1a3d66c6d9c4.png)

**Comment by nashaofu** [comment]
请注意在electronBuilder的配置里面去配置，你现在的vue.config.js里面会启动两个webpack，所以你要搞清楚，你是在哪个webpack里面配置的

**Comment by fjl280855990** [comment]
谢谢，就是这个原因

**Comment by moyongqing** [comment]
> 谢谢，就是这个原因

你好请问下最后怎么改呢
