### ISSUE TITLE
打包后启动程序就报错：找不到模块（Cannot find module ‘electron-screenshots’）

### ISSUE THREAD

**Issue by fjl280855990** [nashaofu/screenshots#32]

**Comment by WenWenBo** [comment]
所以这是什么原因呢，我也出现这个问题了。求解！

**Comment by nashaofu** [comment]
https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#%E6%B3%A8%E6%84%8F

**Comment by WenWenBo** [comment]
> https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md#%E6%B3%A8%E6%84%8F

![image](https://user-images.githubusercontent.com/34451040/156277969-3d750fbb-f8fa-428e-bf81-e75ade3b7fba.png)

webpack已经配置了，但是打包出来的包里面没有electron-screenshots这个包，感觉是electron-builder打包的配置问题。

**Comment by nashaofu** [comment]
参考这个看看https://github.com/nashaofu/dingtalk

**Comment by wangzj141** [comment]
我也有同样的问题
![image](https://user-images.githubusercontent.com/5604075/195233565-6b298dc4-d710-4035-9787-320875205764.png)

**Comment by wangzj141** [comment]
我也有类似的问题，打包安装后，启动提示这个。
![image](https://user-images.githubusercontent.com/5604075/195233773-74f176af-02aa-493b-a6c8-9eae931dd98e.png)

**Comment by nashaofu** [comment]
还有这个问题？
