### ISSUE TITLE
打包异常

### ISSUE THREAD

**Issue by BenTuTu** [nashaofu/screenshots#33]
Electron + React:开发环境可以正常运行，打包出现如下问题

![image](https://user-images.githubusercontent.com/33352279/81916700-b9d5fb00-9606-11ea-80b2-d01bf714a8c5.png)

**Comment by nashaofu** [comment]
https://github.com/nashaofu/screenshots/blob/master/packages/electron-screenshots/README.md 按文档里这样做就好了
![image](https://user-images.githubusercontent.com/19303058/82004253-fbad8280-9694-11ea-8470-a3c1ce23b01c.png)

**Comment by BenTuTu** [comment]
感谢 可以了，是我这边merge的问题
