### ISSUE TITLE
尝试为react-screenshots包加入了路径拖拽，文字绘制等功能

### ISSUE THREAD

**Issue by Hilbertangers** [nashaofu/screenshots#34]
嗨，我fork了一份代码，为react-screenshots包加入了路径拖拽编辑，文件绘制编辑等等功能，体验上做到了和企业微信的截图差不多，这是仓库地址，README里有预览[url](https://github.com/Hilbertangers/screenshots)，如果您觉得满意，我可以提一个pr

**Comment by nashaofu** [comment]
看了一下做得挺好的，你修改好了就合并过来吧

**Comment by Hilbertangers** [comment]
@nashaofu 已经提[https://github.com/nashaofu/screenshots/pull/35/commits/7c38a0d6036192409d48ce65668f191dde8768d1](pr)了，不过我放到electron测试时有两个问题，还要麻烦你解决下：
- 截图窗口不响应键盘，导致文字无法输入
- css cursor失效

**Comment by nashaofu** [comment]
新的功能已经发布到新版本了

**Comment by Hilbertangers** [comment]
@nashaofu 我上面提的那俩问题 是macOS系统的兼容，我提了pr，可以review下
