### ISSUE TITLE
mac的retain屏截图模糊

### ISSUE THREAD

**Issue by nicksun011** [nashaofu/screenshots#36]
mac的retain屏截图模糊

**Comment by nashaofu** [comment]
最新版吗？

**Comment by nicksun011** [comment]
是的，0.0.6版本
![20200521142127313](https://user-images.githubusercontent.com/3025042/82529883-92cf7a00-9b6e-11ea-8f8b-c8000ef460e1.png)

其他截图软件效果
![其他截图软件](https://user-images.githubusercontent.com/3025042/82529903-9c58e200-9b6e-11ea-8d48-954f5a99ba67.jpg)

**Comment by nashaofu** [comment]
我看看
