### ISSUE TITLE
electron-vue的index.js中调用startCapture()报错

### ISSUE THREAD

**Issue by jazzwsr** [nashaofu/screenshots#38]
![image](https://user-images.githubusercontent.com/8381304/83402489-6a326480-a439-11ea-9684-db45e6855dc5.png)

![image](https://user-images.githubusercontent.com/8381304/83401794-2f7bfc80-a438-11ea-8589-6e54ade90ca0.png)
报错如图示截图无响应，请问是否为webpack的配置问题？

**Comment by nashaofu** [comment]
你使用的electron是什么版本

**Comment by jazzwsr** [comment]
electronVersion: 4.2.12

**Comment by jazzwsr** [comment]
> 你使用的electron是什么版本

 electronVersion:: 4.2.12

**Comment by nashaofu** [comment]
使用6以上吧
