### ISSUE TITLE
添加插件以后，我的应用无法退出，必须使用强制退出才能退出

### ISSUE THREAD

**Issue by gouxiwen** [nashaofu/screenshots#4]

**Comment by nashaofu** [comment]
你在退出应用前请先调用截图对象的`destroy`方法，这个方法会销毁截图对象https://github.com/nashaofu/shortcut-capture#methods

**Comment by chenweijianGZ** [comment]
> _No description provided._
我也遇到过，可以检查一下你关闭时程序是否只关闭了主窗口（mainWin），而插件截图的方法是新建一个新窗口，所以退出时要把所有窗口销毁，才能关闭app，官网获取所有窗口方法为BrowserWindow.getAllWindows(),返回数组，希望能帮到你
