### ISSUE TITLE
Electron-vue里面直接使用readme里面的代码无反应啊

### ISSUE THREAD

**Issue by rockyxia** [nashaofu/screenshots#5]
我是在Electron-vue搭建的项目里面，刚搭建的空项目，直接安装了`npm i shortcut-capture`，注册了快捷键`ctrl+alt+b`,没有出现截屏的功能

**Comment by nashaofu** [comment]
报错好像是浏览器插件报错吧，你可以不用快捷键，直接调用shortcutCapture.shortcutCapture()方法看看，会不会出现截屏界面

**Comment by Jocs** [comment]
@nashaofu 我也遇到了相同的问题，发现是在开发环境时启动截图窗口的html 路径出了问题。我的workaround 如下：

```js
   this.shortcutCapture = new ShortcutCapture()
    if (process.env.NODE_ENV === 'development') {
      // 下面的代码需要根据实际项目结构修改
      this.shortcutCapture.dirname = path.resolve(path.join(__dirname, '../../../node_modules/shortcut-capture'))
    }
```

目的使得 `this.shortcutCapture.dirname` 指向 node_modules 中 shortcut-capture。

希望作者能够解决这个问题。thanks！

**Comment by nashaofu** [comment]
好的，我会优化的

**Comment by zhangjunling521** [comment]
解决了吗？目前我的也是不能出现截图页面，和你的情况一样，你是这么解决的呢

**Comment by Jocs** [comment]
@zhangjunling521 https://github.com/nashaofu/shortcut-capture/issues/5#issuecomment-494066036

**Comment by zhangjunling521** [comment]
我是用electron-vue搭建的项目单页面开发，用了你的方法还是没反应，shortcutCapture.dirname这个路径我打印出来是正确的。@Jocs

**Comment by Jocs** [comment]
我也是用的electron-vue啊，你需要再看看路径


发自我的 iPhone

**Comment by nashaofu** [comment]
已经发布新版本，新版本的路径问题请参考https://github.com/nashaofu/shortcut-capture#usage 中的注意事项, electron-vue使用是正常的，如果还是不能解决，请使用以下配置

webpack配置要修改为如下配置：
```js
{
  externals: {
    'shortcut-capture': 'require("shortcut-capture")'
  }
}
```

**Comment by zpx1123** [comment]
externals: {
    'shortcut-capture': 'require("shortcut-capture")'
  } 加进去了， 也不行

**Comment by nashaofu** [comment]
> externals: {
> 'shortcut-capture': 'require("shortcut-capture")'
> } 加进去了， 也不行

@zpx1123 你是修改的主进程的webpack配置吧

**Comment by zpx1123** [comment]
@nashaofu  已解决了， 我用的是Vue CLI Plugin Electron Builder， 有点区别，

**Comment by fjl280855990** [comment]
@zpx1123 你是怎么解决的呢，我也遇到同样的问题。。。

**Comment by nashaofu** [comment]
vue-cli-plugin-electron-builder参考这里
https://github.com/nashaofu/vue-cli-plugin-electron-builder-issue/blob/0f774a90b09e10b02f86fcb6b50645058fe1a4e8/vue.config.js#L1-L8

```js
// vue.config.js
module.exports = {
  publicPath: '.',
  pluginOptions: {
    electronBuilder: {
      // 不打包，使用 require 加载
      externals: ['shortcut-capture']
    }
  }
}
```
