### ISSUE TITLE
resizing and moving property is always false

### ISSUE THREAD

**Issue by DazzlingBeing** [nashaofu/screenshots#56]
when screenshots.startCapture(), resize the selection or move it, then click ok button. from the event ok callback, the CaptureData.Bounds, resizing and moving is always false, like:  { resizing: false, x1: 99, y1: 184, x2: 677, y2: 332, moving: false }.

**Comment by nashaofu** [comment]
resizing and moving are redundant keys. I will delete this parameter in the next version.
