### ISSUE TITLE
Windows上中文输入的时候候选字位置不对

### ISSUE THREAD

**Issue by nicksun011** [nashaofu/screenshots#58]
Windows上中文输入的时候候选字位置不对

![image](https://user-images.githubusercontent.com/3025042/101230098-6b8d6400-36de-11eb-8203-8495719c4163.png)

另外就是双击保存这个能否加个配置选项，可以配置掉，现在经常误操作。可能是双击判断的有问题，经常两次间隔较长的单击的时候就保存了

**Comment by nashaofu** [comment]
双击截图改善了以下使用体验，输入文字问题还没能解决，因为我这边没复现

**Comment by nicksun011** [comment]
我用你的工程本地调试的时候就没有问题，用npm包里的就有。用的是微软拼音。这块react我不是太熟悉哈。是不是你可以加我一起看看呢

**Comment by nicksun011** [comment]
和输入法有关，微软输入法问题比较大，搜狗的好一些
