### ISSUE TITLE
边缘点击无效

### ISSUE THREAD

**Issue by canvascat** [nashaofu/screenshots#6]
在使用了透明窗口后，窗口边框5px以内的区域无法响应任何DOM事件，所以无法从左上角开始截图。

**Comment by nashaofu** [comment]
你把截图的窗口吗？还是你本身应用的窗口？请提供详细一点的信息

**Comment by nashaofu** [comment]
你好，你录制的视屏我这边看不了，我感觉应该是我这边把窗体设置为透明导致的

**Comment by nashaofu** [comment]
你是什么系统？

**Comment by yz1231** [comment]
@nashaofu 
系统：windows10
我也觉得是`transparent`的问题，因为不使用`transparent`的时候就不会存在这个问题。
可以做截图功能的话这个属性又贴别需要。😂
