### ISSUE TITLE
解决截图黑屏问题后引入了开始截图时界面会先黑再变为透明

### ISSUE THREAD

**Issue by cyj-cpu** [nashaofu/screenshots#63]
解决截图黑屏问题后引入了开始截图时界面会先黑再变为透明

**Comment by nashaofu** [comment]
什么系统呢？

**Comment by cyj-cpu** [comment]
linux系统，之前用的版本是0.10，后面出现黑屏换到最新的版本，发现截图的时候闪

**Comment by nashaofu** [comment]
linux 什么发行版呢？我这边好下载安装测试

**Comment by cyj-cpu** [comment]
这个好像是基于Redhat发行版改的，具体版本我也看不了

**Comment by nashaofu** [comment]
好像是因为linux系统不支持透明背景，目前不太能修复。后续我这边再看看是否有其他方法
