### ISSUE TITLE
win10家庭版系统上截图会发生闪退问题

### ISSUE THREAD

**Issue by Wrste** [nashaofu/screenshots#77]
希望开发者老哥看看是怎么回事，有没有遇到这个问题的老哥

**Comment by nashaofu** [comment]
electron什么版本

**Comment by Wrste** [comment]
> electron什么版本

electron是8.5.5     electron-screenshots 是 0.0.14

**Comment by Wrste** [comment]
> electron什么版本

不得不说老哥开发的截图框架很好用，我也积极推荐给身边的开发者朋友了，祝老哥顺意，再次感谢了!

**Comment by nashaofu** [comment]
你能提供运行例子吗？我这边没有win10家庭版

**Comment by Wrste** [comment]
具体什么样的运行例子,目前的情况是在win10家庭版点击截图整个软件就会崩溃关闭，没有任何提示。有的设置一下兼容模式win8也能运行，但是有一部分直接不行。

**Comment by nashaofu** [comment]
你提供一个能复现问题的git仓库吧，然后我这边clone下来看看


-------- 原始邮件 --------
发件人： fxc ***@***.***>
日期： 2021年4月26日周一 10:55
收件人： nashaofu/screenshots ***@***.***>
抄送： nashaofu ***@***.***>, Comment ***@***.***>
主 题： Re: [nashaofu/screenshots] win10家庭版系统上截图会发生闪退问题 (#77)

具体什么样的运行例子,目前的情况是在win10家庭版点击截图整个软件就会崩溃关闭，没有任何提示。有的设置一下兼容模式win8也能运行，但是有一部分直接不行。

―

**Comment by Wrste** [comment]
就是v0.0.14版本，系统版本Windows10家庭中文版

**Comment by Wrste** [comment]
我大概排除了一下，应该是窗口隐藏之后，调用截图出现问题，然后没收到回调事件窗口没有显示，但是进程有程序线程

**Comment by Wrste** [comment]
老哥检查一下，感谢

**Comment by Wrste** [comment]
我目前在两台Amd的cpu平台遇到过闪退
![image](https://user-images.githubusercontent.com/28056826/117280722-774fa300-ae95-11eb-90e5-b48159f8bfbd.png)
![image](https://user-images.githubusercontent.com/28056826/117280761-80407480-ae95-11eb-82ae-5f50447bc0a7.png)

**Comment by nashaofu** [comment]
你可以clone这个仓库https://github.com/nashaofu/dingtalk，在你电脑上运行一下，看看截图功能有没有问题
