### ISSUE TITLE
拉取截图的时候屏幕会抖动

### ISSUE THREAD

**Issue by kilames** [nashaofu/screenshots#84]
首先感谢大佬的分享，插件很好用！
我现在遇到的问题是这样的，在win10的electron中截屏，拖动的时候选中框周围的分辨率会发生变化，造成一种抖动的效果，猜测是因为canvas绘图的时候分辨率变化导致的，但是在mac里目前没有发现这个情况
希望大佬看一下这个问题

**Comment by kilames** [comment]
1080P的屏幕，验证了一下应该是缩放比例设置的问题，笔记本推荐的缩放比例是125%，如果调成100%就不会发生抖动的情况，如果调成150%，这个抖动的情况会比以前更严重一些

**Comment by nashaofu** [comment]
确实存在这个问题

**Comment by nashaofu** [comment]
发布了最新版本，不知道是否还存在这个问题
