### ISSUE TITLE
如何增加鼠标右键取消截图能力

### ISSUE THREAD

**Issue by qdhaiqiang** [nashaofu/screenshots#89]
您好，

参考微信截图行为，想做自定义的调整，请指教下应该怎么去实现？

1. 自定义快捷键
2. 截图时鼠标右键，取消截图

谢谢

**Comment by nashaofu** [comment]
这个需要更改我这边的代码才行

**Comment by qdhaiqiang** [comment]
这两个都是需要您提供支持的吗？
因为现在微信几乎就是一切即时通讯软件的标杆，所以客户有这两个需求的来源，希望这个截图组件也能提供一下这两个需求的支持。

谢谢。

**Comment by nashaofu** [comment]
后面考虑支持，下个版本加上

**Comment by nashaofu** [comment]
新版本已经支持
