### ISSUE TITLE
屏幕分辨率175%的时候截图唤不起，调整到150%及以下就可以

### ISSUE THREAD

**Issue by crystalHan1** [nashaofu/screenshots#98]

**Comment by nashaofu** [comment]
windows对吗？

**Comment by bruceauyeung** [comment]
@nashaofu 这是由于在不同的屏幕缩放比下，getDisplayNearestPoint 返回的bound里面的宽高不是整数导致的。用math.floor处理下即可。我们在使用过程中也遇到了，是这么分析解决的。

**Comment by crystalHan1** [comment]
> @nashaofu 这是由于在不同的屏幕缩放比下，getDisplayNearestPoint 返回的bound里面的宽高不是整数导致的。用math.floor处理下即可。我们在使用过程中也遇到了，是这么分析解决的。有空我提个pr吧。

感谢解答，问题已解决。
